Add camera zoom and pan controls
TheAdamSmith/precursor pull request #19
Opened 2024-02-21 04:29 UTC by wchaney98

Spent way too long getting the camera pan "velocity" to work decently, but was fun to get working. 
* Added script to Camera in `planet_level.tscn` with zoom/pan functionality
* Adjusted same Camera to use "Position Smoothing" - can also easily be turned off 
* Input mappings for zoom/pan in Project Settings: middle mouse scroll to zoom, middle mouse press to pan
* Default window mode to windowed, just easier to debug, but can adjust if we want to keep fullscreen default

![Godot_v4 2 1-stable_win64_FmfcSk5rc6](https://github.com/TheAdamSmith/precursor/assets/12282139/c0ed3032-86db-41b7-9e09-173a279fc6b7)

2024-02-25 17:58 UTC, mitchellkazin15 requested changes
This works great! Can you add controller options for this too? I'm thinking pan with right stick, re-center by pushing in right stick or something

2024-02-26 01:34 UTC, wchaney98 commented
> This works great! Can you add controller options for this too? I'm thinking pan with right stick, re-center by pushing in right stick or something

Tried implementing that. Also have it so holding L2 + right stick up/down zooms the camera in/out as well

2024-02-29 19:01 UTC, TheAdamSmith approved these changes
🔥 This is dope. Thanks for doing this. It will be nice while we are building. 

I like the default to windowed for now since I always switch it to that for myself.

One minor nit: the panning on controller is pretty slow. But I wouldn't let that hold up merge as I don't think I will be adjusting camera too much with controller

2024-03-01 02:58 UTC, mitchellkazin15 approved these changes

2024-03-01 02:59 UTC, merged