Ruslan branch
TheAdamSmith/precursor pull request #20
Opened 2024-02-26 05:20 UTC by ninja-rage

Created an alien thing with move and attack animations. 
![alien-v1-attack1](https://github.com/TheAdamSmith/precursor/assets/159506373/1398637b-50f5-4551-9fb9-6fa0a1f7101c)
![alien-v1-attack2](https://github.com/TheAdamSmith/precursor/assets/159506373/6fb988f5-a80b-4898-a968-a4c9ad679f52)
![alien-v1-move1](https://github.com/TheAdamSmith/precursor/assets/159506373/843fb5cc-b2d6-43e3-aa22-fb7c4ce3f887)
![alien-v1-move2](https://github.com/TheAdamSmith/precursor/assets/159506373/338ae35b-9728-4b77-83d6-77f266b3d537)

Added an Enemy node with a script that follows the player Node. The move animation plays while moving, attack animation plays if collision with the player Node is detected.

2024-03-01 02:30 UTC, TheAdamSmith approved these changes
Hell yeah! the animation looks dope

2024-03-01 02:30 UTC, TheAdamSmith commented on README.md
> +# whiteboard: https://miro.com/online-whiteboard/board/DiCFMAgWH3QUpYjjMjHVkQzdFTJD0uEp/
nice

2024-03-01 02:30 UTC, TheAdamSmith commented on levels/planet_level/pla18D6.tmp
> +texture = ExtResource("5_drr3i")
what are these files

2024-03-01 02:30 UTC, TheAdamSmith commented on enemies/enemy.gd
> +@onready var player = get_node("/root/Level/player")
Think this is fine for now. I think that since we will assumably have a lot of enemies. It might make sense to put player position in an autoload https://docs.godotengine.org/en/stable/tutorials/scripting/singletons_autoload.html

2024-03-01 02:30 UTC, TheAdamSmith commented on enemies/enemy.gd
> +	var overlaps = %AttackBox.get_overlapping_bodies()
what does the `%` do?

2024-03-01 23:13 UTC, ninja-rage commented on levels/planet_level/pla18D6.tmp
> +texture = ExtResource("5_drr3i")
I have no clue, I saw some weird files on other pull requests so thought this was normal. I'll try deleting them and add to the git ignore.

2024-03-01 23:19 UTC, ninja-rage commented on enemies/enemy.gd
> +	var overlaps = %AttackBox.get_overlapping_bodies()
It was used in the tutorial I was following. Reading a bit about it, it sounds like it's an alternative to get_node().
https://docs.godotengine.org/en/stable/tutorials/scripting/gdscript/gdscript_basics.html
![image](https://github.com/TheAdamSmith/precursor/assets/159506373/6732bfa5-c51f-4ede-87c0-b8778a8ef3b0)

2024-03-03 14:31 UTC, mitchellkazin15 requested changes
Looks good so far! Could you make it flip directions if the player is on the right side of it

2024-03-03 21:29 UTC, ninja-rage commented
> Looks good so far! Could you make it flip directions if the player is on the right side of it

yes but I can see of 2 different ways of doing it. Also our enemies should probably follow the same pattern. So, do we want to make all of our enemies looking left, and then flip the sprite when its walking right or should we create separate animations for left/right. Can go either way but we should probably figure out the standard. Also open to other ideas.

2024-03-03 23:20 UTC, mitchellkazin15 approved these changes

2024-03-05 17:48 UTC, merged