Enemy spawn system
TheAdamSmith/precursor pull request #34
Opened 2024-04-18 05:10 UTC by ninja-rage

added a script for instantiating and spawning enemies. Currently the spawning happens randomly, only thing necessary is to know the name of the loaded resource. 

This works by saving the resource inside the enemyAnimatesSprite2D folder, loading it by name, and then adding it to an instantiated enemy.tscn child.

2024-04-18 19:45 UTC, mitchellkazin15 requested changes
Tested and it works great! Just left a couple minor comments. Need to merge main as well

2024-04-18 19:45 UTC, mitchellkazin15 commented on levels/spawn_enemies.gd
To keep with the composition design pattern, can you give this a `class_name` and make it a child node of the level scene instead of directly attaching it as the level script

2024-04-18 19:45 UTC, mitchellkazin15 commented on levels/spawn_enemies.gd
> +var xBoundary = 2000
Can you add `@export` statements to these boundary vars so  the scripts logic can be reused on different sized levels/arena

2024-04-18 19:45 UTC, mitchellkazin15 commented on levels/spawn_enemies.gd
> +	var enemySprite = load("res://enemies/enemyAnimatedSprite2D/" + enemyModel + ".tscn").instantiate()
Nice! This logic will be useful in a lot of places going forward I think (choosing different player models, arenas, guns, etc)

2024-04-19 10:54 UTC, ninja-rage commented on levels/spawn_enemies.gd
not sure if I did this correctly :o

2024-04-19 11:32 UTC, ninja-rage commented
Tested it, should be good to go. Merge conflicts were minimal and also added the group stuff. @mitchellkazin15 lmk if there's anything else to fix.

2024-04-19 20:46 UTC, ninja-rage commented on levels/spawn_enemies.gd
ok i think i did it lol

2024-04-19 21:54 UTC, mitchellkazin15 requested changes

2024-04-19 21:54 UTC, mitchellkazin15 commented on levels/planet_level/planet_level.tscn
> +[ext_resource type="Script" path="res://levels/spawn_enemies.gd" id="1_on5qm"]
Just gotta remove this line now by right clicking the "Level" node and click "Detach Script". Right now effectively double enemies are spawning since 2 nodes are running the spawn enemy script

2024-04-20 00:11 UTC, ninja-rage commented on levels/planet_level/planet_level.tscn
> +[ext_resource type="Script" path="res://levels/spawn_enemies.gd" id="1_on5qm"]
script detached, thanks for the guide lol.

2024-04-20 01:43 UTC, mitchellkazin15 approved these changes
Nice work!

2024-04-20 02:42 UTC, merged