27 send over creeps to other player when you kill them
TheAdamSmith/precursor pull request #56
Opened 2024-08-09 19:51 UTC by wchaney98

New CreepSendComponent attached to player2 and computer_player scenes which trigger spawning of creeps in other arenas whenever the bar at the bottom is filled up

2024-08-10 01:22 UTC, mitchellkazin15 requested changes
Nice work on this so far!

2024-08-10 01:22 UTC, mitchellkazin15 commented on shaders/glow.gdshader
> +	for (float x= -glow_radius; x <= glow_radius; x += 1.0) {
I'm a little confused about these `for` loops. It seems like it samples the pixels around our current pixel and kind of averages them into the glow color, is that correct?

2024-08-10 01:22 UTC, mitchellkazin15 commented on characters/enemies/enemy_spawner.gd
>  func spawn_enemy():
First thing in this function we should check `if disabled: return`. Now after the computers die it will continue to spawn and it gets laggy fast if we want to hit "Continue"

2024-08-13 02:29 UTC, wchaney98 commented on characters/enemies/enemy_spawner.gd
>  func spawn_enemy():
fixed

2024-08-13 02:30 UTC, wchaney98 commented on shaders/glow.gdshader
> +	for (float x= -glow_radius; x <= glow_radius; x += 1.0) {
Something like that, that's about my depth of understanding it as well. I got it from this vid: https://www.youtube.com/watch?v=zHWth5vTY-4

2024-08-13 02:30 UTC, wchaney98 commented on autoloads/event_service.gd
> +	for n in sending_player.owner.find_children("", "EnemySpawner"):
Added `get_spawner_by_arena_name` func and dict that maps arena names to their `EnemySpawner` class obj

2024-08-13 02:31 UTC, wchaney98 commented on characters/components/creep_send_component.gd
> +		times_sent += 1
Tweaked to send x number of creeps where x is the lvl of the player sending creeps

2024-08-13 02:31 UTC, wchaney98 commented on characters/enemies/enemy_spawner.gd
> +	num_enemies_spawned += 1
fixed

2024-08-13 02:31 UTC, wchaney98 commented on characters/enemies/enemy_spawner.gd
> +	enemy.experience_given = _enemy_exp
fixed

2024-08-13 02:32 UTC, wchaney98 commented on characters/components/creep_send_component.gd
> +		next_send_value = next_send_value + 10
done

2024-08-13 02:32 UTC, wchaney98 commented on characters/components/creep_send_component.gd
> +func add_progress(value: float):
😎

2024-08-13 02:32 UTC, wchaney98 commented on characters/components/creep_send_component.gd
> +@export
fixed

2024-08-16 02:30 UTC, mitchellkazin15 approved these changes
Looks good, thanks for making these changes!

2024-08-17 01:36 UTC, merged